name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-forge:
    name: Build Forge
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false

    - name: Cache ForgeGradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches/forge_gradle
          ~/.gradle/caches/minecraft
        key: ${{ runner.os }}-forgegradle-${{ hashFiles('Forge/build.gradle', 'Forge/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-forgegradle-

    - name: Make gradlew executable
      run: chmod +x Forge/gradlew

    - name: Build Forge with Gradle Wrapper
      run: cd Forge && ./gradlew build --no-daemon

    - name: Upload Forge Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Forge-build-artifacts
        path: Forge/build/libs/*.jar
        if-no-files-found: error
        retention-days: 5