name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-fabric:
    name: Build Fabric
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make gradlew executable
      run: chmod +x Fabric/gradlew

    - name: Build Fabric with Gradle Wrapper
      run: cd Fabric && ./gradlew build

    - name: Upload Fabric Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: fabric-build-artifacts
        path: Fabric/build/libs/*.jar
        if-no-files-found: error
        retention-days: 5

  build-neoforge:
    name: Build NeoForge
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make gradlew executable
      run: chmod +x NeoForge/gradlew

    - name: Build NeoForge with Gradle Wrapper
      run: cd NeoForge && ./gradlew build

    - name: Upload NeoForge Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: neoforge-build-artifacts
        path: NeoForge/build/libs/*.jar
        if-no-files-found: error
        retention-days: 5